apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: calculator
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
      - name: calculator
        image: kpnreg.azurecr.io/calculator:$version
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: acr-registry
