apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
      - name: calculator
        image: kpnreg.azurecr.io/calculator:13
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 300m
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
      imagePullSecrets:
      - name: acr-registry
